import CalculateIcon from "@mui/icons-material/Calculate";
import Calculator from "./components/MathCalculator/Calculator";
import AgeCalculator from "./components/AgeCalculator/AgeCalculator";
import TextCaseConverter from "./components/TextCases/TextCaseConverter";

const toolsList = [
    {
        id: "calculator",
        title: "Math Calculator",
        path: "calculator",
        component: <Calculator />,
        icon: <CalculateIcon />,
        description: "",
        isActive: true,
    },
    {
        id: "age-calculator",
        title: "Age Calculator",
        path: "age-calculator",
        component: <AgeCalculator />,
        icon: <CalculateIcon />,
        description: "",
        isActive: true,
    },

    // Text case tools (nested under 'text-case')
    {
        id: "uppercase",
        title: "Uppercase",
        path: "uppercase",
        component: <TextCaseConverter caseType="uppercase" />,
        icon: <CalculateIcon />,
        description: "",
        group: "text-case",
        isActive: true,
    },
    {
        id: "lowercase",
        title: "Lowercase",
        path: "lowercase",
        component: <TextCaseConverter caseType="lowercase" />,
        icon: <CalculateIcon />,
        description: "",
        group: "text-case",
        isActive: true,
    },
    {
        id: "capitalize",
        title: "Capitalize",
        path: "capitalize",
        component: <TextCaseConverter caseType="capitalize" />,
        icon: <CalculateIcon />,
        description: "",
        group: "text-case",
        isActive: true,
    },
    {
        id: "title-case",
        title: "Title Case",
        path: "title-case",
        component: <TextCaseConverter caseType="title-case" />,
        icon: <CalculateIcon />,
        description: "",
        group: "text-case",
        isActive: true,
    },
    {
        id: "sentence-case",
        title: "Sentence Case",
        path: "sentence-case",
        component: <TextCaseConverter caseType="sentence-case" />,
        icon: <CalculateIcon />,
        description: "",
        group: "text-case",
        isActive: true,
    },
    {
        id: "toggle-case",
        title: "Toggle Case",
        path: "toggle-case",
        component: <TextCaseConverter caseType="toggle-case" />,
        icon: <CalculateIcon />,
        description: "",
        group: "text-case",
        isActive: true,
    },
    {
        id: "camel-case",
        title: "Camel Case",
        path: "camel-case",
        component: <TextCaseConverter caseType="camel-case" />,
        icon: <CalculateIcon />,
        description: "",
        group: "text-case",
        isActive: true,
    },
    {
        id: "pascal-case",
        title: "Pascal Case",
        path: "pascal-case",
        component: <TextCaseConverter caseType="pascal-case" />,
        icon: <CalculateIcon />,
        description: "",
        group: "text-case",
        isActive: true,
    },
    {
        id: "snake-case",
        title: "Snake Case",
        path: "snake-case",
        component: <TextCaseConverter caseType="snake-case" />,
        icon: <CalculateIcon />,
        description: "",
        group: "text-case",
        isActive: true,
    },
    {
        id: "screaming-snake-case",
        title: "Screaming Snake Case",
        path: "screaming-snake-case",
        component: <TextCaseConverter caseType="screaming-snake-case" />,
        icon: <CalculateIcon />,
        description: "",
        group: "text-case",
        isActive: true,
    },

    {
        id: "kebab-case",
        title: "Kebab Case",
        path: "kebab-case",
        component: <TextCaseConverter caseType="kebab-case" />,
        icon: <CalculateIcon />,
        description: "",
        group: "text-case",
        isActive: true,
    },
    {
        id: "train-case",
        title: "Train Case",
        path: "train-case",
        component: <TextCaseConverter caseType="train-case" />,
        icon: <CalculateIcon />,
        description: "",
        group: "text-case",
        isActive: true,
    },
    {
        id: "dot-case",
        title: "Dot Case",
        path: "dot-case",
        component: <TextCaseConverter caseType="dot-case" />,
        icon: <CalculateIcon />,
        description: "",
        group: "text-case",
        isActive: true,
    },
    {
        id: "path-case",
        title: "Path Case",
        path: "path-case",
        component: <TextCaseConverter caseType="path-case" />,
        icon: <CalculateIcon />,
        description: "",
        group: "text-case",
        isActive: true,
    },
    {
        id: "cobol-case",
        title: "Cobol Case",
        path: "cobol-case",
        component: <TextCaseConverter caseType="cobol-case" />,
        icon: <CalculateIcon />,
        description: "",
        group: "text-case",
        isActive: true,
    },
];

export default toolsList;
